### ISSUE TITLE
Compatibility with non-english default language

### ISSUE THREAD

**Issue by remyvv** [FacetWP/facetwp-wpml#2]
When using WPML with another default language then english, it is common practice to leave the string translations source language in english.
This means however that if i, for example, create a multilingual site with dutch and english as languages where dutch is the default language, the FacetWP - WPML string translation would not function because of this check:
https://github.com/FacetWP/facetwp-wpml/blob/master/facetwp-wpml.php#L139

I would like to propose to change this method to this:
https://gist.github.com/remyvv/b52fd2a6e676923c17183751c7364490

This way FacetWP always asks WPML for the correct translation.

If i should open a PR instead, let me know!

**Comment by mgibbs189** [comment]
@remyvv so the source strings are in a different language from the site default?

That IF statement makes sure that `icl_translate` only runs when necessary (since it's a fairly slow function). Instead of removing that IF statement, what if I added a filter like so?:

```php
$force_translate = apply_filters( 'facetwp_wpml_force_translate', false );

if ( $lang != $default || $force_translate ) {
```

**Comment by remyvv** [comment]
@mgibbs189 Yes the source strings are in English because WPML String Translations expects them to be in English, but the sites default language is Dutch.
A filter would be a good approach indeed!
Maybe you could even set `$force_translate` to `true` if `$default !== 'en'`? Because that would fix the problem automatically for users with a non-english default language.

**Comment by mgibbs189** [comment]
Closing. I think the original strings need to be in the same language as the site default...

**Comment by remyvv** [comment]
For any future readers:
I eventually figured out that you can define a source language inside the WPML string translations menu, so i re-configured FacetWP in the site default languages, and told WPML to translate form that language instead of the default english.
