### ISSUE TITLE
Incompatibility with last version of wpml

### ISSUE THREAD

**Issue by mdorchain** [FacetWP/facetwp-wpml#3]
Hi,

it seems that icl_translate is not working anymore.

return icl_translate( 'FacetWP', $string, false, false, $has_translation, $string );

might need to be replaced by 

return apply_filters( 'wpml_translate_single_string', $string, 'FacetWP', $string, $lang );

After the that, the string translations are found.

tnx

Michael

**Comment by mgibbs189** [comment]
@mdorchain Thanks for reporting, I'll check it out.

So re-indexing and everything else works fine, to your knowledge?

**Comment by mdorchain** [comment]
@mgibbs189 Both methods are still working. wpml hasn't removed icl_translate yet so no need to rush.
Swapping the different ways of getting the translations had no effect on the indexing or results.

During the tests, I noticed that the add_filter( 'facetwp_i18n', array( $this, 'facetwp_i18n' ) ); in the init is not necessary. With the line 34 commented, wpml still translates the labels even without the filter being called.

The label_only strings still need to be translated separately in the functions.php using the 'facetwp_i18n filter. They probably shouldn't even be registered in wpml I think.

**Comment by mgibbs189** [comment]
Thanks.

That `facetwp_i18n` filter is in place to handle any DB-based strings that WPML wouldn't be able to detect, e.g. the "Any" placeholder text for Dropdown facets.

**Comment by mdorchain** [comment]
The filter provided in facet-wpml had no effect on the label_any on my end. I had to hook myself and provide the translated string in the functions.php the usual way without wpml.

I did bang my head a few times on that issue, but I'm sure about it now :)

**Comment by mgibbs189** [comment]
Hey @mdorchain just checking in... have you run into any other WPML compatibility issues since making this change?

**Comment by mdorchain** [comment]
Hi Matt, 
I ended up disabling the facetwp_i18n filter in this plugin and run my own. 
I could not get the labels translated without proceeding this way.

**Comment by mgibbs189** [comment]
@mdorchain could you tell me more? E.g. show me the code you mean by "running my own"? WPML still seems to be biting me in the butt a bit :)

**Comment by mdorchain** [comment]
Sure I'll be happy to help if I can.
So I noticed that the registration of the string seems to work fine, as far as I remember WPML is detecting all the strings declared like the labels, the "any".

Last time we exchanged about it, the issue came from the display of the translations.
The current facet_i18n filter for wpml wasn't working properly. It was simply not getting the translations.

So I hooked on the facetwp_i18n in the functions.php my own as follow:

```
function paclaw_facetwp_i18n($string) {

        if (!isset(FWP()->facet->http_params['lang'])) {
                return $string;
        }

        $lang = FWP()->facet->http_params['lang'];

        // manual translations
        $translations = array();
		$translations[ 'zh-hans' ][ 'Name' ]			 = '姓名';
		$translations[ 'zh-hans' ][ 'Start typing...' ]	 = '开始输入';

		$translations[ 'zh-hans' ][ 'Locations' ]	 = '办公地点';
		$translations[ 'zh-hans' ][ 'Any Location' ] = '任何办公地点';

		$translations[ 'zh-hans' ][ 'Practice Areas' ]		 = '执业领域';
		$translations[ 'zh-hans' ][ 'Any Practice Area' ]	 = '任何执业领域';

		$translations[ 'zh-hans' ][ 'Industries' ]	 = '行业';
		$translations[ 'zh-hans' ][ 'Any Industry' ] = '任何行业';

		$translations[ 'zh-hans' ][ 'Roles' ]	 = '职位';
		$translations[ 'zh-hans' ][ 'Any Role' ] = '任何职位';

		$translations[ 'zh-hans' ][ 'Languages' ]	 = '语言';
		$translations[ 'zh-hans' ][ 'Any Language' ] = '任何语言';

        if (isset($translations[$lang][$string])) {
                return $translations[$lang][$string];
        }

        return $string;
}

add_filter('facetwp_i18n', 'paclaw_facetwp_i18n');
```

Nothing fancy just a simple implementation of facetwp_i18n.

I retested today with the latest version of the plugins.
Everything seems to work fine. The hook in the functions.php isn't necessary anymore.
WPML had few significant updates recently, that's the only explaination ...

I guess it won't help you much :(

**Comment by mgibbs189** [comment]
Interesting, thanks! So it sounds like the WPML integration is working properly now, for you at least (without needing that custom `facetwp_i18n1` filter).

**Comment by mdorchain** [comment]
Yes it looks like it's working so far :)

**Comment by mgibbs189** [comment]
@mdorchain Great, thanks for the update!
